
#ifndef _HK_SEGFONT_H
#define _HK_SEGFONT_H
//---------------------------------------------------------------------------
//#define segA  (1<<0)
//#define segB  (1<<6)
//#define segC  (1<<5)
//#define segD  (1<<3)
//#define segE  (1<<2)
//#define segF  (1<<1)
//#define segG  (1<<7)
//#define segDP (1<<4)

#define segA  (1<<5)
#define segB  (1<<7)
#define segC  (1<<1)
#define segD  (1<<3)
#define segE  (1<<4)
#define segF  (1<<6)
#define segG  (1<<0)
#define segDP (1<<2)
//---------------------------------------------------------------------------
#define  sym_0 (segA | segB | segC | segD | segE | segF)
#define  sym_1 (segB | segC)
#define  sym_2 (segA | segB | segD | segE | segG)
#define  sym_3 (segA | segB | segC | segD | segG)
#define  sym_4 (segB | segC | segF | segG)
#define  sym_5 (segA | segC | segD | segF | segG)
#define  sym_6 (segA | segC | segD | segE | segF | segG)
#define  sym_7 (segA | segB | segC)
#define  sym_8 (segA | segB | segC | segD | segE | segF | segG)
#define  sym_9 (segA | segB | segC | segD | segF | segG)
//---------------------------------------------------------------------------
#define  syme_A     (segA | segB | segC | segE | segF | segG)
#define  syme_B     (segC | segD | segE | segF | segG)
#define  syme_C     (segA | segD | segE | segF)
#define  syme_D     (segB | segC | segD | segE | segG)
#define  syme_E     (segA | segD | segE | segF | segG)
#define  syme_F     (segA | segE | segF | segG)
#define  syme_G     (segA | segC | segD | segE | segF)
#define  syme_H     (segB | segC | segE | segF | segG)
#define  syme_I     (segC)
#define  syme_J     (segB | segC | segD)
#define  syme_K     (segE | segF | segG)
#define  syme_L     (segD | segE | segF)
#define  syme_M     (segB | segC | segE | segF)
#define  syme_N     (segC | segE | segG)
#define  syme_O     (segC | segD | segE | segG)
#define  syme_P     (segA | segB | segE | segF | segG)
#define  syme_Q     (segA | segB | segC | segF | segG)
#define  syme_R     (segE | segG)
#define  syme_S     (sym_5)
#define  syme_T     (segD | segE | segF | segG)
#define  syme_U     (segB | segC | segD | segE | segF)
#define  syme_V     (segC | segD | segE)
#define  syme_W     (segD)
//---------------------------------------------------------------------------
#endif //_HK_SEGFONT_H
