
#define TIM_COUNT 9

const TIM_DRV_T tim_list[TIM_COUNT] = {
// 0
{ TIM1, &(RCC->APB2ENR), RCC_APB2ENR_TIM1EN, F_APB2_TIM},
// 1
{ TIM2, &(RCC->APB1ENR), RCC_APB1ENR_TIM2EN, F_APB1_TIM },
// 2
{ TIM3, &(RCC->APB1ENR), RCC_APB1ENR_TIM3EN, F_APB1_TIM },
// 3
{ TIM6, &(RCC->APB1ENR), RCC_APB1ENR_TIM6EN, F_APB1_TIM },
// 4
{ TIM7, &(RCC->APB1ENR), RCC_APB1ENR_TIM7EN, F_APB1_TIM },
// 5
{ TIM14, &(RCC->APB1ENR), RCC_APB1ENR_TIM14EN, F_APB1_TIM },
// 6
{ TIM15, &(RCC->APB2ENR), RCC_APB2ENR_TIM15EN, F_APB2_TIM },
// 7
{ TIM16, &(RCC->APB2ENR), RCC_APB2ENR_TIM16EN, F_APB2_TIM },
// 8
{ TIM17, &(RCC->APB2ENR), RCC_APB2ENR_TIM17EN, F_APB2_TIM }
};

